version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=spa_demo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    restart: always
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./app:./app
    depends_on:
      - backend
  nginx:
    container_name: nginx
    image: proxy
    build: ./.nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443